### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by HuifengShrimp** [kubershahi/mphasis_ppml#1]
How does the mnist dataset generate from the python file?

**Comment by kubershahi** [comment]
The MNIST dataset used by us is not on the repo cause it was too large to commit but I have a zipped file here: https://github.com/kubershahi/ashoka-capstone/tree/master/datasets. This might help.

**Comment by HuifengShrimp** [comment]
Thank you.  But there also exists another problem when I tried to run your program. When testing logistic regression, I found it said that "Segmentation fault (core dumped)".
